name: PHPStan Analysis

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.php'
  push:
    branches:
      - main
    paths:
      - '**/*.php'

jobs:
  phpstan:
    name: Run PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Change the PHP version as needed

      - name: Install dependencies
        run: |
          composer install

      - name: Run PHPStan
        run: |
          vendor/bin/phpstan analyse
